-- Harden story view counting against simple inflation attacks.
-- Run this in Supabase SQL Editor before deploying the updated /api/views route.

begin;

-- Ensure the canonical counter exists on stories.
alter table public.stories
  add column if not exists views bigint;

update public.stories
set views = 0
where views is null;

alter table public.stories
  alter column views set default 0;

alter table public.stories
  alter column views set not null;

-- One row per unique viewer fingerprint per story per UTC day.
create table if not exists public.story_view_events (
  id bigint generated by default as identity primary key,
  story_id text not null references public.stories(id) on delete cascade,
  viewer_key text not null,
  ip_key text not null,
  user_agent text,
  view_day date not null default (timezone('utc', now())::date),
  created_at timestamptz not null default now()
);

create unique index if not exists story_view_events_story_viewer_day_uq
  on public.story_view_events (story_id, viewer_key, view_day);

create index if not exists story_view_events_story_created_idx
  on public.story_view_events (story_id, created_at desc);

create index if not exists story_view_events_ip_day_idx
  on public.story_view_events (ip_key, view_day);

-- Daily attempt counter per story + IP bucket.
create table if not exists public.story_view_ip_daily (
  story_id text not null references public.stories(id) on delete cascade,
  ip_key text not null,
  view_day date not null default (timezone('utc', now())::date),
  attempts integer not null default 0,
  last_seen_at timestamptz not null default now(),
  primary key (story_id, ip_key, view_day)
);

create or replace function public.record_story_view(
  p_story_id text,
  p_viewer_key text,
  p_ip_key text,
  p_user_agent text default null,
  p_max_attempts integer default 200
)
returns table (
  counted boolean,
  views bigint,
  blocked boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_attempts integer;
  v_inserted integer;
  v_views bigint;
begin
  if p_story_id is null or btrim(p_story_id) = '' then
    return;
  end if;

  if not exists (select 1 from public.stories s where s.id = p_story_id) then
    return;
  end if;

  insert into public.story_view_ip_daily (story_id, ip_key, view_day, attempts, last_seen_at)
  values (p_story_id, p_ip_key, timezone('utc', now())::date, 1, now())
  on conflict (story_id, ip_key, view_day)
  do update
    set attempts = public.story_view_ip_daily.attempts + 1,
        last_seen_at = now()
  returning attempts into v_attempts;

  if v_attempts > greatest(p_max_attempts, 1) then
    select coalesce(s.views, 0)::bigint
    into v_views
    from public.stories s
    where s.id = p_story_id;

    return query select false, coalesce(v_views, 0), true;
    return;
  end if;

  insert into public.story_view_events (story_id, viewer_key, ip_key, user_agent, view_day)
  values (
    p_story_id,
    p_viewer_key,
    p_ip_key,
    left(coalesce(p_user_agent, ''), 200),
    timezone('utc', now())::date
  )
  on conflict (story_id, viewer_key, view_day) do nothing;

  get diagnostics v_inserted = row_count;

  if v_inserted > 0 then
    update public.stories s
    set views = coalesce(s.views, 0) + 1
    where s.id = p_story_id
    returning coalesce(s.views, 0)::bigint into v_views;

    return query select true, coalesce(v_views, 0), false;
    return;
  end if;

  select coalesce(s.views, 0)::bigint
  into v_views
  from public.stories s
  where s.id = p_story_id;

  return query select false, coalesce(v_views, 0), false;
end;
$$;

revoke all on function public.record_story_view(text, text, text, text, integer) from public;
grant execute on function public.record_story_view(text, text, text, text, integer) to service_role;

commit;
